language: node_js
node_js:
- 6.2.0
branches:
  only:
  - master
before_script:
- npm install -g bower
- npm install -g gulp
- npm install -g firebase-tools
script:
- bower install
- gulp deploy
- firebase deploy --token ${FIREBASE_TOKEN}
