language: node_js
node_js:
  - 9.10.1
cache: yarn
branches:
  only:
    - master
before_script:
  - npm install
  - npm install -g firebase-tools@7.2.2
script:
  - npm run build
  - firebase deploy --token ${FIREBASE_TOKEN}
