language: node_js
node_js:
- 9.10.1
cache: yarn
branches:
  only:
  - master
before_script:
- yarn install
- yarn global add firebase-tools
script:
- yarn run build
- firebase deploy --token ${FIREBASE_TOKEN}
