language: node_js
node_js:
  - 9.10.1
cache: npm
branches:
  only:
    - master
install:
  - npm install
  - npm install -g firebase-tools@7.2.2
script:
  - npm run build
  - firebase deploy --token ${FIREBASE_TOKEN}
