name: Deploy to prod

on:
  push:
    branches: [ master, deploy-manual ]
  workflow_dispatch:


concurrency:
  group: prod
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 9.10.1
        cache: 'npm'
    - name: "Install dependencies"
      run: npm install
    - name: "Build"
      run: npm run build
    - name: "Deploy"
      run: npm run deploy
      env:
        FIREBASE_TOKEN: "${{ secrets.FIREBASE_TOKEN}}"



