name: Deploy to prod

on:
  push:
    branches: [ master, deploy-manual ]
  workflow_dispatch:


concurrency:
  group: prod
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - uses: borales/actions-yarn@v3.0.0
    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: build
    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: deploy
      env:
        FIREBASE_TOKEN: "${{ secrets.FIREBASE_TOKEN}}"



